version: "3"
services:
  postgres:
    image: postgres:13.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - -p 5433
    environment:
      POSTGRES_DB: "groups"
      POSTGRES_USER: "groups"
      POSTGRES_PASSWORD: "groups"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./setup/database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
    
  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.10.0
    environment:
      DATA_SOURCE_URI: "postgres:5433/groups?sslmode=disable"
      DATA_SOURCE_USER: "groups"
      DATA_SOURCE_PASS: "groups"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    networks:
      - postgres

  bot:
    build: ./
    ports:
      - "8443-8543:8443-8543"
      - "443:443"
    restart: always
    networks:
      - postgres

networks:
  postgres:
    driver: bridge