version: '3.3'

services:

  postgres:
    image: postgres:13.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - -p 5434
    environment:
      POSTGRES_DB: "groups"
      POSTGRES_USER: "groups"
      POSTGRES_PASSWORD: "groups"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./setup/database:/docker-entrypoint-initdb.d
      - ./setup:/var/lib/postgresql/data
    ports:
      - "5434:5434"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - default
    
  db-exporter:
    container_name: db_exporter_cont    
    image: prometheuscommunity/postgres-exporter:v0.10.0
    environment:
      DATA_SOURCE_URI: "postgres:5434/groups?sslmode=disable"
      DATA_SOURCE_USER: "groups"
      DATA_SOURCE_PASS: "groups"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/postgres_exporter/queries.yaml"
    volumes:
      - ./setup/queries.yaml:/postgres_exporter/queries.yaml:ro
    ports:
      - "9188:9188"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    networks:
      - default
 
  grafana:
    image: grafana/grafana
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./setup/grafana:/var/lib/grafana
      - ./setup/grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default
  
  bot:
    build: ./
    ports:
      - "8400-8443:8400-8443"
    restart: always
    links:
      - postgres
      - db-exporter
      - grafana
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16