name: Server-Setup

on:
  push:
    branches:
    - main
    
jobs:
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to host via SSH and update containers
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          user: ${{ secrets.USER }}
          command: |
          
              if [ -d ./tg_welcome_bot ]
              then 
                cd tg_welcome_bot
                docker-compose down
                git pull
              else
                git clone https://github.com/mtvy/tg_welcome_bot.git
                cd tg_welcome_bot
                pip install -r setup/requirements.txt
              fi
            
              echo "TOKEN=$TOKEN" > setup/.env
              docker-compose up -d --build
              
        shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
            